name: openai_prompt_runner
description: Minimal harness for automated mass executions of prompts against OpenAI or Azure endpoints
version: 1.0.0
repository: https://github.com/maxim-saplin/openai_prompt_runner

environment:
  sdk: ^3.0.3

# Add regular dependencies here.
dependencies:
  http:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
